badge:
  stage: deploy
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_BRANCH
  script:
    - mkdir -p public
    - |
      RAW="$CI_COMMIT_TITLE"
      SHORT=$(printf "%.12s" "$RAW")

      if [ "${#RAW}" -gt 12 ]; then
        TITLE="${SHORT}.."
      else
        TITLE="$RAW"
      fi

      cat > public/commit-badge.json <<EOF
      {
        "schemaVersion": 1,
        "label": "Nightly",
        "message": "$TITLE",
        "color": "9b59b6"
      }
      EOF
  artifacts:
    paths:
      - public/commit-badge.json
    public: true
pages:
  stage: deploy
  script:
    - echo "Publishing Pages"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
