# Prints in the console, whenever a javascript has been loaded
# by default, scripts that failed to load will print in the console
PrintScriptActivations: true

# Logs in the console, whenever a placeholder gets
# registered or unregistered
LogPlaceHolderActivity: true

# Logs in the console, whenever a custom command
# gets enabled/loaded or disabled/removed
LogCustomCommandsActivity: true

# Will send messages regarding errors and warnings to operators or users who have
# the permission to use the commands from OpenJS
BroadcastToOps: true

# Checks for updates and notifies admins and the console for an update
# you can disable this, but it is better to stay up to date
UpdateNotifications: true

# Automatically reloads scripts when they are changed
# Changes include: modifications, creations and deletions
# Scripts that are also newly created will be loaded automatically
AutoReloadScriptsOnChange: true

# If enabled, the Old class importer introduced in 1.3.0 will be used.
# It is recommended to keep this disabled,
# because the old importer does not translate Java classes
UseOldClassImporter: false

# opt-in/out from Bstats https://bstats.org/plugin/bukkit/OpenJavaScript/22268
AllowBstats: true

# enable/disable debug mode, only use if you encounter bugs or issues with OpenJS
# eats up a lot of performance
debugMode: false